/** ODAY OS — Graphite + Lime design tokens (mobile copy for EAS builds) */

export const ODAY_PRIMITIVES = {
  black950: '#111210',
  black900: '#161614',
  black850: '#1C1C1A',
  black800: '#1C1C1A',
  line800: '#2A2A28',
  paper50: '#F4F4F0',
  paper100: '#ECECE7',
  paper200: '#DCDDD7',
  warm300: '#9A9C95',
  warm500: '#6F716B',
  lime: '#C7FF3D',
  limeDeep: '#A8D92F',
  graphite: '#242522',
  danger500: '#B45F55',
  dangerSoft: '#F3E7E5',
  success500: '#61705A',
  successSoft: '#E9ECE6',
  white: '#FFFFFF',
  placeholder: '#6F716B',
  tabInactive: '#A9A89F',
};

export const ODAY_COLORS = {
  paper: ODAY_PRIMITIVES.paper50,
  dot: ODAY_PRIMITIVES.paper100,
  ink: ODAY_PRIMITIVES.black950,
  inkSoft: ODAY_PRIMITIVES.warm500,
  inkFaint: ODAY_PRIMITIVES.warm300,
  tint: ODAY_PRIMITIVES.paper100,
  sidebar: ODAY_PRIMITIVES.black950,
  sidebarSoft: ODAY_PRIMITIVES.graphite,
  sidebarLine: ODAY_PRIMITIVES.line800,
  sidebarText: ODAY_PRIMITIVES.warm300,
  sidebarTextFaint: ODAY_PRIMITIVES.warm500,
  sidebarTitle: ODAY_PRIMITIVES.paper50,
  bronze1: ODAY_PRIMITIVES.lime,
  bronze2: ODAY_PRIMITIVES.limeDeep,
  bronzeLine: ODAY_PRIMITIVES.line800,
  burgundy: ODAY_PRIMITIVES.danger500,
  burgundySoft: ODAY_PRIMITIVES.dangerSoft,
  burgundyLine: ODAY_PRIMITIVES.danger500,
  emerald: ODAY_PRIMITIVES.success500,
  emeraldSoft: ODAY_PRIMITIVES.successSoft,
  emeraldLine: ODAY_PRIMITIVES.success500,
  border: ODAY_PRIMITIVES.paper200,
  card: ODAY_PRIMITIVES.white,
  focus: ODAY_PRIMITIVES.black950,
  lime: ODAY_PRIMITIVES.lime,
  limeDeep: ODAY_PRIMITIVES.limeDeep,
  white: ODAY_PRIMITIVES.white,
};

export const ODAY_PALETTE = {
  id: 'graphite-brass',
  name: 'ODAY OS',
  swatches: [ODAY_PRIMITIVES.black950, ODAY_PRIMITIVES.lime, ODAY_PRIMITIVES.warm500, ODAY_PRIMITIVES.paper50],
  sidebarDark: true,
  colors: {
    paper: ODAY_COLORS.paper,
    dot: ODAY_COLORS.dot,
    ink: ODAY_COLORS.ink,
    inkSoft: ODAY_COLORS.inkSoft,
    inkFaint: ODAY_COLORS.inkFaint,
    tint: ODAY_COLORS.tint,
    sidebar: ODAY_COLORS.sidebar,
    sidebarSoft: ODAY_COLORS.sidebarSoft,
    sidebarLine: ODAY_COLORS.sidebarLine,
    sidebarText: ODAY_COLORS.sidebarText,
    sidebarTextFaint: ODAY_COLORS.sidebarTextFaint,
    sidebarTitle: ODAY_COLORS.sidebarTitle,
    bronze1: ODAY_COLORS.bronze1,
    bronze2: ODAY_COLORS.bronze2,
    bronzeLine: ODAY_COLORS.bronzeLine,
    burgundy: ODAY_COLORS.burgundy,
    burgundySoft: ODAY_COLORS.burgundySoft,
    burgundyLine: ODAY_COLORS.burgundyLine,
    emerald: ODAY_COLORS.emerald,
    emeraldSoft: ODAY_COLORS.emeraldSoft,
    emeraldLine: ODAY_COLORS.emeraldLine,
    border: ODAY_COLORS.border,
    card: ODAY_COLORS.card,
    focus: ODAY_COLORS.focus,
  },
};

export const ODAY_SHADOW = {
  shadowColor: ODAY_PRIMITIVES.black950,
  shadowOpacity: 0.08,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const ODAY_LOGIN = {
  black950: ODAY_PRIMITIVES.black950,
  black850: ODAY_PRIMITIVES.black850,
  black800: ODAY_PRIMITIVES.black800,
  line800: ODAY_PRIMITIVES.line800,
  paper50: ODAY_PRIMITIVES.paper50,
  warm300: ODAY_PRIMITIVES.warm300,
  warm500: ODAY_PRIMITIVES.warm500,
  gold400: ODAY_PRIMITIVES.lime,
  gold500: ODAY_PRIMITIVES.limeDeep,
  danger: ODAY_PRIMITIVES.danger500,
  success: ODAY_PRIMITIVES.success500,
  placeholder: ODAY_PRIMITIVES.placeholder,
};
